services:
  ollama-webui:
    image: lucifero19/ollama-webui:latest
    build: .
    container_name: ollama-webui
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - ollama-network

  backend:
    image: lucifero19/ollama-backend:latest
    build: ./backend
    container_name: ollama-backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
